version: '3.7'
services: 
  db:
    image: postgres
    container_name: joindev-postgres-container
    restart: always
    environment: 
      POSTGRES_PASSWORD: joindev
    volumes: 
      - ./api/db/data:/var/lib/postgres
    ports: 
      - '5432:5432'
  api:
    build: './api'
    container_name: joindev-node-container
    restart: always
    volumes: 
      - ./api:/home/node/app
    ports: 
      - '4000:4000'
    depends_on: 
      - db